# Generated by Django 5.0.6 on 2024-06-20 02:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("member", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="reg_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
